### ISSUE TITLE
Crashes on CL131382

### ISSUE THREAD

**Issue by Kubrix** [satisfactorymodding/SatisfactoryModManager#68] opened 2020-10-17 18:36 UTC
Satisfactory CL131382 - experimental branch
SMM 2.2.1.0 - modded profile created
Windows 7 Pro SP1
No mod installed

How to get a crash:
Download any mod and start gane via SMM
In the game accept the ealry access
Choose exit to desktop

No crashes when no mod in installed (crashes when using PermaDay and Lizard Doggo Spawner

**Comment by mircearoata** [comment] 2020-10-17 19:54
This is not related to SMM. The issue is SML logging too early which stops UE from closing the log file correctly

**Closed by mircearoata** 2020-10-17 19:54 UTC
