### ISSUE TITLE
Satisfactory Mod Manager loads, but does not show on any monitor and stays in taskbar

### ISSUE THREAD

**Issue by XactlyAverage** [satisfactorymodding/SatisfactoryModManager#155] opened 2022-07-05 20:55 UTC
So i used to use mod manager on satisfactory with epic games store, but have since brought on steam instead as i prefer using steam. 

Since that, i removed, and then reinstalled mod manager, however now when i launch it, the programme runs, but i cant see it on any monitor. 

If i alt+tab, it shows there, and if i hover over the icon in the taskbar it shows there as well, but i cannot see it, and cannot use it.

I tried changing the properties and selecting start maximised, but that also didnt help.

**Comment by budak7273** [comment] 2022-08-03 20:21
The issue is that the window somehow got offscreen. To fix it you need to go in `%appdata%\SatisfactoryModManager\settings.json` and in `windowLocation` set the x and y to 0 to bring the window back on the screen. Restart SMM after you do that.

**Comment by mircearoata** [comment] 2022-11-13 10:15
Duplicate of #154

**Closed by mircearoata** 2022-11-13 10:15 UTC
