### ISSUE TITLE
Bug: Highlight buttons in mod list not unhighlighting properly

### ISSUE THREAD

**Issue by AngelSkyheart** [satisfactorymodding/SatisfactoryModManager#135] opened 2021-11-27 00:17 UTC
rrently whenever you move your mouse over the pause/play or install/uninstall buttons in the left list of your mods the image changes to highlight what your mouse is currently hovering over. Then when you move your mouse back off of it, sometimes the highlight changes back to the unhighlighted version... and sometimes it doesn't. It's really aggravating and bugs me a lot. Can you please fix this? It generally tends to happen when I'm moving my mouse quickly across the screen and it happens to go over multiple buttons at once. 
It never seems to happen with the favorites button though.
Seriously, please make it stop. It's so annoying.
![Screenshot from 2021-11-26 19-11-24](https://user-images.githubusercontent.com/54604305/143662143-64551d38-3f2e-4655-8136-704b0ad156c1.png)
..

**Comment by mircearoata** [comment] 2021-11-27 09:29
Duplicate of #125, I have already fixed this, and will release the new version (along with a lot of other stuff) today.

**Comment by mircearoata** [comment] 2021-11-27 12:24
Fixed in v2.6.0

**Closed by mircearoata** 2021-11-27 12:24 UTC
